#!/bin/bash

# NOTE:
# Requires VirtualBox Guest Additions
#
# TODO: 
# 1. Combine vmstate and vmip since vmip relies on vmstate
# 2. Test on a server with multiple IP addresses 
#

args=("$@")
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
LIST_FILE=$FILE_DIR"/vm.list"
LOG_FILE=$FILE_DIR"/vm.log"

# Preparation
VMLIST=()
while IFS=$'\n' read -a config
do
  VMLIST+=("${config}")
done < $LIST_FILE

# Handle Commands
missing=true
if [ $# -ne 1 ]
  then
    echo "Invalid Parameters"
else
  for vm in "${VMLIST[@]}"
  do
    if [ "$1" == "--all" ] || [ "$1" == "$vm" ]
      then
        missing=false
        online=$(vboxmanage showvminfo "$vm" | grep -c "running" )
        if [ $online -eq 0 ]; then
          echo "VM \"$vm\" is currently offline"
        else
          ip=$(VBoxManage guestproperty get "$vm" "/VirtualBox/GuestInfo/Net/0/V4/IP" | grep -Eo '[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}')
          if [ "$ip" == "" ]; then
            echo "Could not find field, please confirm that guest has vbox guest additions installed"
          else
            echo "VM \"$vm\" is on: "$ip
          fi
        fi
    fi
  done
  if $missing ; then
    echo "No VM \"$1\" registered"
  fi
fi

