#!/bin/bash

args=("$@")
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
FUNC_FILE=$FILE_DIR"/vm.functions"

. $FUNC_FILE
VALID_COUNT=($(vboxmanage list vms | wc -l))

if [ $# -eq 0 ]; then
  for vm in "${VMLIST[@]}"; do
    valid_println "VM \"${vm}\" is registered"
  done
elif [ $# -eq 1 ]; then
  missing=true
  for vm in "${VMLIST[@]}"; do
    if [ "$1" == "--all" ] || [ "$1" == "$vm" ]; then
      missing=false
      valid_println "VM \"${vm}\" is registered"
    fi
  done
  index=1
  while [ $index -le $VALID_COUNT ]; do
    VALID_VM="$(vboxmanage list vms | cut -d \" -f2 | head -n $index | tail -n 1)"
    if [ "$1" == "--all" ] || [ "$1" == "--valid" ] || [ "$VALID_VM" = "$1" ]; then
      missing=false
      echo "VM \"$VALID_VM\" is valid"
    fi
    index=$[$index+1]
  done
  if $missing ; then
    invalid_println "No VM \"$1\" found"
  fi
else
  invalid_println "Invalid parameters"
fi
