#!/bin/bash

args=("$@")
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
LIST_FILE=$FILE_DIR"/vm.list"
LOG_FILE=$FILE_DIR"/vm.log"

VMLIST=()
VALID_COUNT=($(vboxmanage list vms | wc -l))

while IFS=$'\n' read -a vm
do
  VMLIST+=(${vm})
done < $LIST_FILE

if [ $# -eq 0 ]; then
  for vm in ${VMLIST[@]}; do
    echo "VM \"${vm}\" is registered"
  done
elif [ $# -eq 1 ]; then
  missing=true
  for vm in ${VMLIST[@]}; do
    if [ $1 == "--all" ] || [ $1 == $vm ]; then
      missing=false
      echo "VM \"${vm}\" is registered"
    fi
  done
  index=1
  while [ $index -le $VALID_COUNT ]; do
    VALID_VM="$(vboxmanage list vms | cut -d \" -f2 | head -n $index | tail -n 1)"
    if [ $1 == "--all" ] || [ $1 == "--valid" ] || [ "$VALID_VM" = $1 ]; then
      missing=false
      echo "$VALID_VM is valid"
    fi
    index=$[$index+1]
  done
  if $missing ; then
    echo "No VM \"$1\" found"
  fi
else
  echo "Invalid parameters"
fi
