#!/bin/bash

args=("$@")
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
LIST_FILE=$FILE_DIR"/vm.list"
LOG_FILE=$FILE_DIR"/vm.log"

VALID_VMS=($(vboxmanage list vms | grep -oP '"\K[^"\047]+(?=["\047])'))
VMLIST=()
while IFS=$'\n' read -a vm
do
  VMLIST+=(${vm})
done < $LIST_FILE

if [ $# -eq 0 ]; then
  for vm in ${VMLIST[@]}; do
    echo "VM \"${vm}\" is registered"
  done
elif [ $# -eq 1 ]; then
  missing=true
  for vm in ${VMLIST[@]}; do
    if [ $1 == "--all" ] || [ $1 == $vm ]; then
      missing=false
      echo "VM \"${vm}\" is registered"
    fi
  done
  for valid in ${VALID_VMS[@]}; do
    if [ $1 == "--all" ] || [ $1 == $valid ] || [ $1 == "--valid" ]; then
      missing=false
      echo "VM \"$valid\" is a valid VM"
    fi
  done
  if $missing ; then
    echo "No VM \"$1\" found"
  fi
else
  echo "Invalid parameters"
fi
