#!/bin/bash

args=("$@")
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
FUNC_FILE=$FILE_DIR"/vm.functions"

. $FUNC_FILE

function turn_off {
    echo "Turning \"$1\" off"
    vboxmanage controlvm "$1" poweroff 2>>$LOG_FILE
    if [ $? -eq 0 ]; then
        valid_println "Successfully turned \"$1\" off"
    else
        invalid_println "Failed turning \"$1\" off"
    fi
}

if [ $# -lt 1 ]; then
    echo "Invalid parameters"
elif [ $# -eq 1 ] && [ "$1" == "--all" ]; then
    for vm in "${VMLIST[@]}"; do
        turn_off $vm
    done
else
    while [[ $# -gt 0 ]]; do
        param="$1"
        if [[ "  ${VMLIST[@]} " =~ " ${param} " ]]; then
            turn_off $param
        else
            invalid_println "No VM ${param} registered"
        fi
        shift
    done
fi
