#!/bin/bash

args=("$@")
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
FUNC_FILE=$FILE_DIR"/vm.functions"

. $FUNC_FILE

function turn_on {
    if $2 ; then
        echo "Turning on \"${1}\""
        vboxmanage startvm "$1" --type headless 2>>$LOG_FILE
    else
        echo "Launching \"${1}\""
        vboxmanage startvm "$1" 2>>$LOG_FILE
    fi
    if [ $? -ne 0 ]; then
        invalid_println "Failed turning \"$1\" on"
    else
        valid_println "Completed turning \"$1\" on"
    fi
}

if [ $# -lt 1 ]; then
    echo "Invalid parameters"
elif [ $# -eq 1 ] && [ "$1" == "--all" ]; then
    for vm in "${VMLIST[@]}"; do
        turn_on $vm true
    done
else
    while [[ $# -gt 0 ]]; do
        param="$1"
        headless=true
        if [ $param == "--head" ]; then
            headless=false
            param="$2"
            shift
        fi
        if [[ "  ${VMLIST[@]} " =~ " ${param} " ]]; then
            turn_on $param $headless
        else
            invalid_println "No VM ${param} registered"
        fi
        shift
    done
fi
