#!/bin/bash

args=("$@")
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
FUNC_FILE=$FILE_DIR"/vm.functions"

. $FUNC_FILE
# Handle Commands
missing=true
if [ $# -ne 1 ]
  then
    echo "Invalid Parameters"
else
  for vm in "${VMLIST[@]}"
  do
    if [ "$1" == "--all" ] || [ "$1" == "$vm" ]
      then
        missing=false
        echo "Turning \"$vm\" on"
        vboxmanage startvm "$vm" --type headless 2>>$LOG_FILE
        if [ $? -ne 0 ]; then
          invalid_println "Failed turning \"$vm\" on"
        else
          valid_println "Completed turning \"$vm\" on"
        fi
    fi
  done
fi
if $missing ; then
  invalid_println "No VM \"$1\" registered"
fi
