#!/bin/bash

args=("$@")
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
LIST_FILE=$FILE_DIR"/vm.list"
LOG_FILE=$FILE_DIR"/vm.log"

# Preparation
VMLIST=()
while IFS=$'\n' read -a config
do
  VMLIST+=("${config}")
done < $LIST_FILE

# Handle Commands
missing=true
if [ $# -ne 1 ]
  then
    echo "Invalid Parameters"
else
  for vm in "${VMLIST[@]}"
  do
    if [ "$1" == "--all" ] || [ "$1" == "$vm" ]
      then
        missing=false
        echo "Turning \"$vm\" on"
        vboxmanage startvm "$vm" --type headless 2>>$LOG_FILE
        if [ $? -ne 0 ]; then
          echo "Failed turning \"$vm\" on"
        else
          echo "Completed turning \"$vm\" on"
        fi
    fi
  done
fi
if $missing ; then
  echo "No VM \"$1\" registered"
fi
