#!/bin/bash

args=("$@")
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
FUNC_FILE=$FILE_DIR"/vm.functions"

. $FUNC_FILE

# Handle Commands
missing=true
if [ $# -ne 1 ]
  then
    invalid_println "Invalid Parameters"
else
  for vm in "${VMLIST[@]}"
  do
    if [ "$1" == "--all" ] || [ "$1" == "$vm" ]
      then
        missing=false
        online=$(vboxmanage showvminfo "$vm" | grep -c "running" )
        if [ $online -eq 0 ]; then
          invalid_println "\"$vm\" is currently offline"
        else
          valid_println "\"$vm\" is currently online"
        fi
    fi
  done
  if $missing ; then
    invalid_println "No VM \"$1\" registered"
  fi
fi
