#!/bin/bash

args=("$@")
FILE_PATH=$(readlink -f "$0")
FILE_DIR=$(dirname "$FILE_PATH")
LIST_FILE=$FILE_DIR"/vm.list"
LOG_FILE=$FILE_DIR"/vm.log"

# Preparation
VMLIST=()
while IFS=$'\n' read -a config
do
  VMLIST+=(${config})
done < $LIST_FILE

# Handle Commands
missing=true
if [ $# -ne 1 ]
  then
    echo "Invalid Parameters"
else
  for vm in ${VMLIST[@]}
  do
    if [ $1 == "--all" ] || [ $1 == $vm ]
      then
        missing=false
        online=$(vboxmanage showvminfo $vm | grep -c "running" )
        if [ $online -eq 0 ]; then
          echo "$vm is currently offline"
        else
          echo "$vm is currently online"
        fi
    fi
  done
fi
if $missing ; then
  echo "No VM $1 found"
fi
